### ISSUE TITLE
Crashed on Nexus 6P

### ISSUE THREAD

**Issue by GaoShin** [erickok/transdroid#469]
I installed version is 2.5.13 from Google Play Store but it crashed after I pressed home button.Here is the crash log:
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.transdroid.lite, PID: 13214
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ListAdapter android.widget.ListView.getAdapter()' on a null object reference
        at org.transdroid.core.gui.TorrentsFragment.updateViewVisibility(TorrentsFragment.java:467)
        at org.transdroid.core.gui.TorrentsFragment.updateIsLoading(TorrentsFragment.java:445)
        at org.transdroid.core.gui.TorrentsActivity.onTorrentsRetrieved(TorrentsActivity.java:1310)
        at org.transdroid.core.gui.TorrentsActivity_.access$201(TorrentsActivity_.java:44)
        at org.transdroid.core.gui.TorrentsActivity_$5.run(TorrentsActivity_.java:283)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by erickok** [comment]
Thanks. I am not sure how this can happen -- I cannot reproduce yet. Is this persistent for you? What torrent client have you set up to use?

**Comment by GaoShin** [comment]
Not persistent ,just sometimes.I add 3 servers,one transmission server and two qbittorrent servers.Sometimes after press back button and wait for few seconds , the crash dialog may show up.Does this crash relate to what server I have chosen before?
