### ISSUE TITLE
Transdrone new crash

### ISSUE THREAD

**Issue by GaoShin** [erickok/transdroid#483]
When I select a low speed connection server and then press back button immediately,the application crash.
I can see error log from Android Studio:

> 2019-01-03 09:42:57.413 428-448/? E/SurfaceFlinger: Failed to find layer (org.transdroid.lite/org.transdroid.core.gui.TorrentsActivity_#0) in layer parent (no-parent).
2019-01-03 09:42:57.449 8405-8405/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.transdroid.lite, PID: 8405
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
        at org.transdroid.core.gui.TorrentsFragment.updateViewVisibility(TorrentsFragment.java:471)
        at org.transdroid.core.gui.TorrentsFragment.updateIsLoading(TorrentsFragment.java:447)
        at org.transdroid.core.gui.TorrentsActivity.onTorrentsRetrieved(TorrentsActivity.java:1311)
        at org.transdroid.core.gui.TorrentsActivity_.access$201(TorrentsActivity_.java:44)
        at org.transdroid.core.gui.TorrentsActivity_$5.run(TorrentsActivity_.java:283)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by paour** [comment]
This is likely the same cause as #484.
