### ISSUE TITLE
Transdroid app crashes

### ISSUE THREAD

**Issue by Vstory** [erickok/transdroid#495]
`java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at org.transdroid.core.gui.TorrentsFragment.updateViewVisibility(TorrentsFragment.java:471)
	at org.transdroid.core.gui.TorrentsFragment.updateIsLoading(TorrentsFragment.java:447)
	at org.transdroid.core.gui.TorrentsActivity.onCommunicationError(TorrentsActivity.java:1296)
	at org.transdroid.core.gui.TorrentsActivity_.access$101(TorrentsActivity_.java:44)
	at org.transdroid.core.gui.TorrentsActivity_$4.run(TorrentsActivity_.java:271)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:6653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
`

Connection and error log:
`
1255 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Schedule server checker job
1256 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Found pending job request{id=100, tag=server_checker, transient=false}, canceling
1257 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=103, tag=server_checker, transient=false}, interval 03:00:00, flex 03:00:00
1258 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Schedule rss checker job
1259 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Found pending job request{id=101, tag=rss_checker, transient=false}, canceling
1260 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=104, tag=rss_checker, transient=false}, interval 03:00:00, flex 03:00:00
1261 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Schedule app update checker job
1262 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Found pending job request{id=102, tag=app_update_checker, transient=false}, canceling
1263 -- Fri Apr 05 02:26:39 GMT+08:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=105, tag=app_update_checker, transient=false}, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
1264 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Run job, request{id=104, tag=rss_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
1265 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Run job, request{id=103, tag=server_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
1266 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Run job, request{id=105, tag=app_update_checker, transient=false}, waited 00:00:00, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
1267 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Executing request{id=103, tag=server_checker, transient=false}, context PlatformJobService
1268 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Executing request{id=104, tag=rss_checker, transient=false}, context PlatformJobService
1269 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Executing request{id=105, tag=app_update_checker, transient=false}, context PlatformJobService
1270 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Finished job{id=104, finished=true, result=SUCCESS, canceled=false, periodic=true, class=RssCheckerJob, tag=rss_checker}
1271 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Finished job, request{id=104, tag=rss_checker, transient=false} SUCCESS
1272 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Skip the update service, as we already checked the last 24 hours (or to be exact at Thu Apr 04 11:42:58 GMT+08:00 2019).
1273 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Finished job{id=105, finished=true, result=RESCHEDULE, canceled=false, periodic=true, class=AppUpdateJob, tag=app_update_checker}
1274 -- Fri Apr 05 02:26:40 GMT+08:00 2019 -- 3 -- Finished job, request{id=105, tag=app_update_checker, transient=false} RESCHEDULE
1275 -- Fri Apr 05 02:26:49 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1276 -- Fri Apr 05 02:26:49 GMT+08:00 2019 -- 3 -- qBittorrent API version is 1
1277 -- Fri Apr 05 02:26:50 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1278 -- Fri Apr 05 02:26:50 GMT+08:00 2019 -- 3 -- qBittorrent API version is 1
1279 -- Fri Apr 05 02:26:59 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1280 -- Fri Apr 05 02:27:00 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1281 -- Fri Apr 05 02:27:09 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1282 -- Fri Apr 05 02:27:09 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1283 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1284 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1285 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.31.108:8012 timed out
1286 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- Success: [{"id":"transdroid","jsonrpc":"2.0","result":[{"bittorrent":{"announceList":[["udp:\/\/tracker.coppersurfer.tk:6969\/announce"],["udp:\/\/tracker.internetwarriors.net:1337\/announce"],["udp:\/\/tracker.opentrackr.org:1337\/announce"],["udp:\/\/9.rarbg.to:2710\/announce"],["udp:\/\/exodus.desync.com:... (2486 chars)
1287 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- aria2: Retrieved torrent listing
1288 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- aria2: 0 new torrents, 0 newly finished torrents.
1289 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- Finished job{id=103, finished=true, result=SUCCESS, canceled=false, periodic=true, class=ServerCheckerJob, tag=server_checker}
1290 -- Fri Apr 05 02:27:10 GMT+08:00 2019 -- 3 -- Finished job, request{id=103, tag=server_checker, transient=false} SUCCESS
1291 -- Fri Apr 05 02:28:57 GMT+08:00 2019 -- 3 -- qBittorrent API version is 23
1292 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ListAdapter android.widget.ListView.getAdapter()' on a null object reference
1293 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsFragment.updateViewVisibility(TorrentsFragment.java:469)
1294 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsFragment.updateIsLoading(TorrentsFragment.java:447)
1295 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity.onTorrentsRetrieved(TorrentsActivity.java:1311)
1296 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_.access$201(TorrentsActivity_.java:44)
1297 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: org.transdroid.core.gui.TorrentsActivity_$5.run(TorrentsActivity_.java:283)
1298 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: android.os.Handler.handleCallback(Handler.java:794)
1299 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:99)
1300 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: android.os.Looper.loop(Looper.java:173)
1301 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6653)
1302 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
1303 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
1304 -- Fri Apr 05 02:29:42 GMT+08:00 2019 -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
1305 -- Fri Apr 05 02:30:02 GMT+08:00 2019 -- 3 -- Schedule server checker job
1306 -- Fri Apr 05 02:30:02 GMT+08:00 2019 -- 3 -- qBittorrent API version is 23
1307 -- Fri Apr 05 02:30:02 GMT+08:00 2019 -- 3 -- Found pending job request{id=103, tag=server_checker, transient=false}, canceling
1308 -- Fri Apr 05 02:30:02 GMT+08:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=106, tag=server_checker, transient=false}, interval 03:00:00, flex 03:00:00
1309 -- Fri Apr 05 02:30:02 GMT+08:00 2019 -- 3 -- Schedule rss checker job
1310 -- Fri Apr 05 02:30:02 GMT+08:00 2019 -- 3 -- Found pending job request{id=104, tag=rss_checker, transient=false}, canceling
1311 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=107, tag=rss_checker, transient=false}, interval 03:00:00, flex 03:00:00
1312 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Schedule app update checker job
1313 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Found pending job request{id=105, tag=app_update_checker, transient=false}, canceling
1314 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=108, tag=app_update_checker, transient=false}, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
1315 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Run job, request{id=108, tag=app_update_checker, transient=false}, waited 00:00:00, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
1316 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Run job, request{id=106, tag=server_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
1317 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Run job, request{id=107, tag=rss_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
1318 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Executing request{id=108, tag=app_update_checker, transient=false}, context PlatformJobService
1319 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Executing request{id=107, tag=rss_checker, transient=false}, context PlatformJobService
1320 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Executing request{id=106, tag=server_checker, transient=false}, context PlatformJobService
1321 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Skip the update service, as we already checked the last 24 hours (or to be exact at Thu Apr 04 11:42:58 GMT+08:00 2019).
1322 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Finished job{id=107, finished=true, result=SUCCESS, canceled=false, periodic=true, class=RssCheckerJob, tag=rss_checker}
1323 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Finished job{id=108, finished=true, result=RESCHEDULE, canceled=false, periodic=true, class=AppUpdateJob, tag=app_update_checker}
1324 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Finished job, request{id=107, tag=rss_checker, transient=false} SUCCESS
1325 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- qBittorrent API version is 23
1326 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Finished job, request{id=108, tag=app_update_checker, transient=false} RESCHEDULE
1327 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- qBittorrent: Retrieved torrent listing
1328 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- qBittorrent: 0 new torrents, 0 newly finished torrents.
1329 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Success: [{"id":"transdroid","jsonrpc":"2.0","result":[{"bittorrent":{"announceList":[["udp:\/\/tracker.coppersurfer.tk:6969\/announce"],["udp:\/\/tracker.internetwarriors.net:1337\/announce"],["udp:\/\/tracker.opentrackr.org:1337\/announce"],["udp:\/\/9.rarbg.to:2710\/announce"],["udp:\/\/exodus.desync.com:... (2486 chars)
1330 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- aria2: Retrieved torrent listing
1331 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- aria2: 0 new torrents, 0 newly finished torrents.
1332 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Finished job{id=106, finished=true, result=SUCCESS, canceled=false, periodic=true, class=ServerCheckerJob, tag=server_checker}
1333 -- Fri Apr 05 02:30:03 GMT+08:00 2019 -- 3 -- Finished job, request{id=106, tag=server_checker, transient=false} SUCCESS
1334 -- Fri Apr 05 02:30:05 GMT+08:00 2019 -- 3 -- qBittorrent API version is 23
`

Rom:MIUI 10 9.4.3 
Android:8.1
Transdroid 2.5.14 (234)
A crash occurred when you pressed the Back button to exit the Transdroid app.

**Comment by Vstory** [comment]
#484 #483
