### ISSUE TITLE
Force-Close when torrent list not empty (qBittorrent server on Android)

### ISSUE THREAD

**Issue by dariusz-goc** [erickok/transdroid#550]
Exception code:

`java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at org.transdroid.daemon.Qbittorrent.QbittorrentAdapter.parseSize(QbittorrentAdapter.java:4)
	at org.transdroid.daemon.Qbittorrent.QbittorrentAdapter.parseJsonTorrents(QbittorrentAdapter.java:29)
	at org.transdroid.daemon.Qbittorrent.QbittorrentAdapter.executeTask(QbittorrentAdapter.java:112)
	at org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:1)
	at org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:5)
	at org.transdroid.core.gui.TorrentsActivity_.access$701(TorrentsActivity_.java:1)
	at org.transdroid.core.gui.TorrentsActivity_$10.execute(TorrentsActivity_.java:1)
	at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)`

**Comment by erickok** [comment]
What version of qBittorrent ae you using?

**Comment by dariusz-goc** [comment]
I use ZetaTorrent on Nvidia SHIELD TV. The app doesn't specify which version it is, but it's free to install.

**Comment by erickok** [comment]
Can you confirm that this is still happening on Transdroid 2.5.18?

**Comment by dariusz-goc** [comment]
Yes, it started with 2.5.17 and is still an issue in 2.5.18.

wt., 9 cze 2020, 11:17 użytkownik Eric Kok <notifications@github.com>
napisał:

**Comment by dariusz-goc** [comment]
Yes, it started with 2.5.17 and is still an issue in 2.5.18.

**Comment by dariusz-goc** [comment]
I'm happy to test any fixes you might have :D

**Comment by dariusz-goc** [comment]
I just parked installed latest version (2.5.19) and the bug is still there:

java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at org.transdroid.daemon.Qbittorrent.QbittorrentAdapter.parseSpeed(QbittorrentAdapter.java:4)
	at org.transdroid.daemon.Qbittorrent.QbittorrentAdapter.parseJsonTorrents(QbittorrentAdapter.java:33)
	at org.transdroid.daemon.Qbittorrent.QbittorrentAdapter.executeTask(QbittorrentAdapter.java:112)
	at org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:1)
	at org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:5)
	at org.transdroid.core.gui.TorrentsActivity_.access$701(TorrentsActivity_.java:1)
	at org.transdroid.core.gui.TorrentsActivity_$10.execute(TorrentsActivity_.java:1)
	at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by erickok** [comment]
Yeah I was fixing one, only for a new one to show up. I'll have to test against ZetaTorrent directly.

**Comment by dariusz-goc** [comment]
Hi, just as a follow up, did you manage to fix this issue?

**Comment by erickok** [comment]
Seems zetaTorrent is dead. Shame.

**Comment by dariusz-goc** [comment]
> Seems zetaTorrent is dead. Shame.

I see that it has been pulled, but it still works for those who have it installed... I can supply you with the apk. The force-close is still there in newer versions of transdroid, I was hoping this would be fixed by now. Older versions work fine.

**Comment by erickok** [comment]
Yup you can send me this and I will debug. I didn't want to download from a random apk 'backup' site as I don't really trust those.

**Comment by erickok** [comment]
Nope those Play Store links do not work for me. I will install from your zip.
