### ISSUE TITLE
bitcomet enter the error password will cause the app to crash

### ISSUE THREAD

**Issue by 1265578519** [erickok/transdroid#645]
bitcomet enter the error password will cause the app to crash
![1](https://user-images.githubusercontent.com/6442439/209312572-6d22d4f4-f1b9-4eca-9e38-184ead254718.jpg)

https://user-images.githubusercontent.com/6442439/209314319-c3be6ff7-2aa9-4008-82eb-af4c4b5be5a9.mp4

**Comment by bwitt** [comment]
I was able to reproduce this and I see the error as
```
E/Transdroid: E: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.transdroid.daemon.Torrent.getUniqueID()' on a null object reference
E/Transdroid: E: org.transdroid.daemon.adapters.bitComet.BitCometAdapter.executeTask(BitCometAdapter.java:149)
E/Transdroid: E: org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:81)
E/Transdroid: E: org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:904)
E/Transdroid: E: org.transdroid.core.gui.TorrentsActivity_.access$701(TorrentsActivity_.java:48)
E/Transdroid: E: org.transdroid.core.gui.TorrentsActivity_$10.execute(TorrentsActivity_.java:359)
E/Transdroid: E: org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:400)
E/Transdroid: E: java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
E/Transdroid: E: java.util.concurrent.FutureTask.run(FutureTask.java:264)
E/Transdroid: E: java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
E/Transdroid: E: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
E/Transdroid: E: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
E/Transdroid: E: java.lang.Thread.run(Thread.java:1012)
E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-4
    Process: org.transdroid.full, PID: 2032
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.transdroid.daemon.Torrent.getUniqueID()' on a null object reference
        at org.transdroid.daemon.adapters.bitComet.BitCometAdapter.executeTask(BitCometAdapter.java:149)
        at org.transdroid.daemon.task.DaemonTask.execute(DaemonTask.java:81)
        at org.transdroid.core.gui.TorrentsActivity.refreshTorrents(TorrentsActivity.java:904)
        at org.transdroid.core.gui.TorrentsActivity_.access$701(TorrentsActivity_.java:48)
        at org.transdroid.core.gui.TorrentsActivity_$10.execute(TorrentsActivity_.java:359)
        at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:400)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```
